name = "jpg-store/marketplace"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'jpg-store/marketplace'"

[repository]
user = "jpg-store"
project = "marketplace"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.1.0"
source = "github"
